version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      - PROD=1
    env_file:
      - ./prod.env
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:create_app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default


  db:
    image: postgres:15-alpine
    ports:
      - "5445:5445"
    environment:
      - POSTGRES_DB=roi
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default


networks:
  default: {}
